### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by startqiu** [ecubus/EcuBus-Pro#12]
在Ubuntu下面npm install报以下错误：
![Screenshot from 2022-01-04 17-17-40](https://user-images.githubusercontent.com/40617107/148036667-bf5b7ad3-170c-4ce6-a572-1d56b36cb6d7.png)
是不支持Linux吗？

**Comment by frankie-zeng** [comment]
是的，目前只支持windows， welcome PR about Linux.

**Comment by mobier** [comment]
可以去掉CAN功能以便支持Linux吗?
