### ISSUE TITLE
npm install出错，提示无法找到打开包括文件“string.h"

### ISSUE THREAD

**Issue by hmf1235789** [ecubus/EcuBus-Pro#14]
参考Build.yml，安装node-14.17.3和最新版本都试过，本地编译，提示无法找到打开包括文件“string.h"和无法打开包括文件”ctype.h"
![1](https://user-images.githubusercontent.com/70952702/150775032-662979f5-26c5-40e7-9ddc-5590e744fb50.png)
![2](https://user-images.githubusercontent.com/70952702/150775053-51be1988-ea01-4fc0-b118-970694fb78d7.png)
![image](https://user-images.githubusercontent.com/70952702/150775169-6488f143-6dcf-4752-b538-ea5b1a86fbe2.png)

**Comment by frankie-zeng** [comment]
应该是node-gyp没有安装好，可以尝试重新安装node.js
