### ISSUE TITLE
dolin  jason 

### ISSUE THREAD

**Issue by ghost** [ecubus/EcuBus-Pro#15]
用LIN 下载时，知乎上面有一个整体的 jason文件，请问这个 jason 文件到哪里下载

**Comment by frankie-zeng** [comment]
可以尝试自己按照自己的需求重新配置

**Comment by JordanYun** [comment]
我是在S32K的源码基础上直接跑demo的，刚刚开始接触LIN，之前没有搞过。我对比了can 的jason文件，LIN 的jason文件应该和can 的差不多？

**Comment by JordanYun** [comment]
另外在测试CAN 时，ECU BUS 下载过程中会出现丢包现象，我买的PEAK是兼容板卡，不知道是不是这个原因。

**Comment by frankie-zeng** [comment]
盗版peak会有这个问题，后续会增加其他usb2can的支持。
