### ISSUE TITLE
无法将函数定义与现有声明匹配

### ISSUE THREAD

**Issue by hmf1235789** [ecubus/EcuBus-Pro#21]
安装好node-gyp后，用msvs2015或msvs2017，npm install提示在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。多个错误，无法将函数定义与现有的声明匹配。
![image](https://user-images.githubusercontent.com/70952702/160275263-2b3115c8-85e0-4295-aa8e-3c68f79e82c7.png)
![image](https://user-images.githubusercontent.com/70952702/160275273-eeb91407-52d4-4ebf-8f2f-e6cb38c33976.png)
![image](https://user-images.githubusercontent.com/70952702/160275283-5709ef0f-d98f-4442-ac6b-87e09d27d30d.png)
该如何解决，非常感谢。

**Comment by frankie-zeng** [comment]
确保  "node-addon-api" 和 noge-gyp 安装正确，拿gyp 编译一个hello world试一下。
可以参考CI的脚步 [build](https://github.com/frankie-zeng/ECUBus/blob/master/.github/workflows/Build.yml)

**Comment by hmsfeng** [comment]
> 确保 "node-addon-api" 和 noge-gyp 安装正确，拿gyp 编译一个hello world试一下。 可以参考CI的脚步 [build](https://github.com/frankie-zeng/ECUBus/blob/master/.github/workflows/Build.yml)

可以给个详细的编译步骤吗？各个工具对应的版本，谢谢了。
