### ISSUE TITLE
A few questions to ask

### ISSUE THREAD

**Issue by zzgg86** [ecubus/EcuBus-Pro#26]
There are a few others I would like to continue to ask:
1. Can you provide 27 security algorithm calculation examples and 31 checksum calculation examples, or save a GROUP containing the above usage?
2. Can the sub-functions of the security algorithm be added, or how to modify the sub-functions that are not in the list?
3. How to insert other non-diagnostic messages into the process?
thank you very much！

**Comment by frankie-zeng** [comment]
![image](https://user-images.githubusercontent.com/43364599/166130792-da2e72cf-3c51-41ba-a6ea-6ca6b4bad41b.png)
[27test.zip](https://github.com/frankie-zeng/ECUBus/files/8598206/27test.zip)
you can use the newest version to open the project.

the example uses node crypto module to do some crypto calculations and put the result into the next service.

also, the second 27 service use a self define subfucntion 66(0x42).

**Comment by zzgg86** [comment]
I'm sorry, I didn't understand your sample code very well. I'm not familiar with js programming. How do I get the seed for the following security algorithm and implement it programmatically. thanks！

void SA_GenerateKey(u8 * RndSeed,u8* key)
{
  unsigned char  MASK[4]={0x12,0x34,0x56,0x78} 
  unsigned char i;
  unsigned char caldata[4]={0};
  for(i=0;i<4;i++)
  {
    caldata[i]=RndSeed[i]^MASK[i];
  }

  key[0]=caldata[3];
  key[1]=caldata[2];
  key[2]=caldata[1];
  key[3]=caldata[0];

}

**Comment by zzgg86** [comment]
I'm sorry, I didn't understand your sample code very well. I'm not familiar with js programming. How do I get the seed for the following security algorithm and implement it programmatically. thanks！

void SA_GenerateKey(u8 * RndSeed,u8* key)
{
  unsigned char  MASK[4]={0x12,0x34,0x56,0x78} 
  unsigned char i;
  unsigned char caldata[4]={0};
  for(i=0;i<4;i++)
  {
    caldata[i]=RndSeed[i]^MASK[i];
  }

  key[0]=caldata[3];
  key[1]=caldata[2];
  key[2]=caldata[1];
  key[3]=caldata[0];

}

**Comment by frankie-zeng** [comment]
![image](https://user-images.githubusercontent.com/43364599/166345780-bcf12521-ecd8-42b4-af53-b320750486dd.png)
![image](https://user-images.githubusercontent.com/43364599/166345796-92a96436-685b-43ca-8c07-b4571c083cab.png)

**Comment by zzgg86** [comment]
Thank you very much, the security algorithm problem has been solved. In addition, regarding the calculation of the checksum of the file, the file can be opened and read, but I don't know how to get the file size? Can you help me out?        
//eg：
this.openFile('FlashDriver.bin','r');
let ptr=this.readFile(1024);
this.info(ptr);

How can I get the size of FlashDriver.bin?

**Comment by frankie-zeng** [comment]
var fs = require("fs"); // Load the filesystem module
var stats = fs.statSync("myfile.txt")
var fileSizeInBytes = stats.size;
// Convert the file size to megabytes (optional)
var fileSizeInMegabytes = fileSizeInBytes / (1024*1024);

**Comment by frankie-zeng** [comment]
this.changeNextFrame("routineControlOptionRecord",crc0.toString(16));

**Comment by zzgg86** [comment]
ECUBUS is very powerful and solves it perfectly. Thank you very much for your support, this software is still very useful. This topic can be closed. Thanks again for the support! In addition, how can physical addressing or functional addressing be configured in each service?

**Comment by frankie-zeng** [comment]
![image](https://user-images.githubusercontent.com/43364599/167053923-1a913cc1-6ae1-4822-96fe-74ec221dfe7e.png)
thanks, you can create multi schedule and assign different addresses to each schedule.

**Comment by zhuanwan223** [comment]
Hello，how does this interface start？

**Comment by eddy-bitsensing** [comment]
Same last issue occured when I set physical/functional can id at the same time. Error message is THE PCAN Hardware is already being used by PCAN-Net. Frankie and zzgg86, Did you guys solve this problem?

**Comment by JOSEPH129009** [comment]
> Thank you for your support, the checksum has been calculated, but now I calculate it in the preload of 31 services, and then modify the preload, but it seems that the checksum value is not sent out in the end, what is the problem? function preLoad(writeData) { .......... this.info(crc0); crc0=crc0^0xFFFFFFFF; this.info(crc0);
> 
> this.changeNextFrame("routineControlOptionRecord",crc0);
> 
> return true; }

Hi @eddy-bitsensing , 
May I ask, How do you write your crc function in the routine control 0x31 to automate the process?
