### ISSUE TITLE
UDS on LIN

### ISSUE THREAD

**Issue by Jason99939** [ecubus/EcuBus-Pro#27]
为什么ECUBus中LIN诊断发送NAD和接收NAD不能相同？NXP SDK中的LIN Stack接收诊断帧和发送响应时NAD都是根据配置的NAD，我应该怎么修改使能可以支持SDK中的LIN Stack?谢谢！
![image](https://user-images.githubusercontent.com/30925279/166626197-247410d0-5840-41cc-b3d3-13f1f5a2eb9a.png)
![image](https://user-images.githubusercontent.com/30925279/166626228-83becb54-0cbd-44ea-8e8d-f02e17e05977.png)

**Comment by frankie-zeng** [comment]
目前ECUBus的send nad不能等于receive nad, 也就是不支持自己发uds帧给自己。
