### ISSUE TITLE
如何增加新的设备驱动， 如Vector CANcase等？

### ISSUE THREAD

**Issue by TysonHu** [ecubus/EcuBus-Pro#31]
如何选择不同的硬件驱动去刷写 ？ 

Vector 提供的有dll文件， 如何调用其中的接口以支持Vector CANcase进行刷写？

**Comment by frankie-zeng** [comment]
熟悉node-addon 的话可以自己开发，参考这个文件。
https://github.com/frankie-zeng/ECUBus/blob/master/src/addons/can/peak/pcantp_napi.cpp
