### ISSUE TITLE
npm install出错

### ISSUE THREAD

**Issue by hmsfeng** [ecubus/EcuBus-Pro#47]
我现在用NPM 10.2.4版本，在npm install时，很多都安装不了。帮忙看看是不是版本不对？
![微信截图_20240304164948](https://github.com/frankie-zeng/ECUBus/assets/7783411/1dc3930c-ae47-4928-b541-6b8e0cf7710b)

**Comment by simonjhy** [comment]
你可以试试node 14试一下
