### ISSUE TITLE
UDS on LIN

### ISSUE THREAD

**Issue by Abor88** [ecubus/EcuBus-Pro#49]
Hello,
Is UDS on LIN supported? I tried sending UDS Default session and I see that Master Request is properly sent with ID = 60 (0x3C) but then I see Slave Response header sent with ID = 125 (0x7D) which is the PID and not the ID of Slave Response frame (I am expecting a frame sent with ID = 61 (0x3D)).
So in my case I see a timeout in Slave response but I have verified with CANoe that my slave is working in Slave response.

**Comment by frankie-zeng** [comment]
Please setup correct NAD， Over LIN is support,  EcuBus as LIN master, will send 0x3c+ data, and 0x3d (header only)

**Comment by Abor88** [comment]
Thank you for you response and your support.
My slave is responding on NAD = 6 so in ECU BUS tool I setup NAD with 
Send NAD = 6
Receive NAD = 0 (since it is not supported to set Send NAD = Receive NAD).
STmin and P2 set as default.
Am I missing something?

**Comment by frankie-zeng** [comment]
makr CAN-OE work as diagnostic only mode.

**Comment by Abor88** [comment]
I have tested my slave with CANoe separately.
Now in my setup I have only ECU BUS connected with a Peak PLIN device. No other tools are opened.

**Comment by frankie-zeng** [comment]
sorry, I mean, you sould config CAN-OE LIN LDF schedule config as diagnostic only mode

**Comment by Abor88** [comment]
Sorry, maybe I am not properly understanding.
I am using only ECU BUS now and no LDF is loaded.
I just opened the tool, configured Response NAD, create 1 UDS project and try to send default session.
What is missing in my setup?

**Comment by frankie-zeng** [comment]
![image](https://github.com/frankie-zeng/ECUBus/assets/43364599/7c15b4cd-86e2-48db-b5b5-162acf86712e)

**Comment by Abor88** [comment]
No ok, I can use CANoe.
The question is why should I use CANoe since I am using ECU Bus only?
Is it no possible to use only ECU BUS?

**Comment by frankie-zeng** [comment]
try to capture the raw log from PLIN-View, 
![image](https://github.com/frankie-zeng/ECUBus/assets/43364599/de548957-ab67-4cf6-8556-53f057894e84)

**Comment by Abor88** [comment]
![lin](https://github.com/frankie-zeng/ECUBus/assets/167741332/414a2f32-12d0-4940-9e06-f5703b45dd6c)

**Comment by frankie-zeng** [comment]
you slave doesn't response, check your slave code.

**Comment by Abor88** [comment]
I can send also the screen of ECU BUS log in debug
![image](https://github.com/frankie-zeng/ECUBus/assets/167741332/512a8715-d533-487d-a336-47abf99a4b32)

The point is this: it seems that the slave is not responding but if I detach it from ECU Bus and on another PC I use CANoe, the slave is always responding

**Comment by frankie-zeng** [comment]
anyway, you need check it in your slave side, why the slave doesn't response...,
